### ISSUE TITLE
Server crash with new version

### ISSUE THREAD

**Issue by DanShu15** [MartenSchaefer/grind-enchantments#2]
Console error and crash while removing 2 enchantments from a fishing pole to a blank book at the grinder
Console:
https://pastebin.com/WRErDij5
Server log:
https://pastebin.com/csY0WYHS
Client log:
https://pastebin.com/WU5KJAhD

I hadn't tested removing an enchantment from a book to a clean book yet, I wanted to grab unbreaking 3 from that pole to combine with another unbreaking 3 that's on a book with other enchantments

**Comment by MartenSchaefer** [comment]
I think I know why this could be happening. I'll try to fix it.

**Comment by MartenSchaefer** [comment]
I think I fixed it with 8ccf4c678fc538ee4c3c707e05c04a07ce2cb52f. I've uploaded a new version to CurseForge, hopefully that works.

**Comment by DanShu15** [comment]
just saw the github update :)
I'll test it on the server ASAP

**Comment by DanShu15** [comment]
Happy to report that the crash is fixed, no errors in the console log, and also that removing enchantments from books does work successfully :)
Great job! Thank you so much!
